"""create property images table

Revision ID: 36562927b90a
Revises: d5208e03ec04
Create Date: 2026-07-23 19:47:53.439199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36562927b90a'
down_revision = 'd5208e03ec04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_images')
    # ### end Alembic commands ###
